name: E2E

on:
  push:
    branches:
      - main
      - 6.x.x

env:
  PERCY_POSTINSTALL_BROWSER: true
  GH_PAGES_OWNER: blackbaud
  GH_PAGES_REPO: skyux-pr-preview

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install-deps:
    name: Install and cache dependencies
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.affected.outputs.projects }}
      e2eMap: ${{ steps.affected.outputs.e2eMap }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            !node_modules/.cache/nx
            /home/runner/.cache/Cypress
          key: cache-pr-preview-${{ hashFiles('package-lock.json') }}
      - name: npm install
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          set -x
          node ./scripts/rebase-pr.js
          npm ci
      - name: Check affected
        id: affected
        run: npx ts-node scripts/github-workflow-e2e-matrix --all

  build-storybook:
    name: Build Project Storybook
    runs-on: ubuntu-latest
    needs: install-deps
    strategy:
      matrix:
        project: ${{ fromJSON(needs.install-deps.outputs.projects) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Retrieve dependencies cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            !node_modules/.cache/nx
            /home/runner/.cache/Cypress
          key: cache-pr-preview-${{ hashFiles('package-lock.json') }}
      - name: Retrieve nx cache
        uses: actions/cache@v2
        with:
          path: |
            .angular
            node_modules/.cache/nx
            dist
          key: cache-nx-storybook-${{ matrix.project }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cache-nx-storybook-${{ matrix.project }}-
            cache-nx-storybook-
            cache-nx-
      - name: Build ${{ matrix.project }}
        run: |
          npx nx run ${{ matrix.project }}:build-storybook:ci --outputDir=dist/storybooks/${{ matrix.project }}
          npx sb extract ./dist/storybooks/${{ matrix.project }}
      - name: Upload storybook artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.project }}
          path: ./dist/storybooks/${{ matrix.project }}
          retention-days: 1
          if-no-files-found: error

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - install-deps
      - build-storybook
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Retrieve dependencies cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            !node_modules/.cache/nx
            /home/runner/.cache/Cypress
          key: cache-pr-preview-${{ hashFiles('package-lock.json') }}
      - name: Retrieve nx cache
        uses: actions/cache@v2
        with:
          path: |
            .angular
            node_modules/.cache/nx
            dist/storybook
          key: cache-nx-publish-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cache-nx-publish-
            cache-nx-
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./dist/storybooks/{{ github.ref_name }}/
      - name: Generate Storybook Composition
        run: npx nx workspace-generator storybook-composition --projectsJson '${{ needs.install-deps.outputs.projects }}' --baseUrl ../storybooks/${{ github.ref_name }}/
      - name: Build Storybook Composition
        run: npx nx run storybook:build-storybook:ci --outputDir=dist/storybook
      - name: Checkout ${{ env.GH_PAGES_REPO }}
        uses: actions/checkout@v3
        with:
          repository: ${{ env.GH_PAGES_OWNER }}/${{ env.GH_PAGES_REPO }}
          ref: 'main'
          fetch-depth: 1
          path: ${{ env.GH_PAGES_REPO }}
          token: ${{secrets.GH_PERSONAL_ACCESS_TOKEN}}
      - name: Publish preview and comment on PR
        run: npx ts-node scripts/github-pages-publish
        env:
          GITHUB_TOKEN: ${{secrets.GH_PERSONAL_ACCESS_TOKEN}}

  e2e:
    name: End to end tests
    runs-on: ubuntu-latest
    needs:
      - install-deps
      - publish
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.install-deps.outputs.e2eMap) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Retrieve dependencies cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            !node_modules/.cache/nx
            /home/runner/.cache/Cypress
          key: cache-pr-preview-${{ hashFiles('package-lock.json') }}
      - name: Percy ${{ matrix.project }}
        run: npx percy exec -- nx run ${{ matrix.project }}-e2e:e2e:ci --skip-nx-cache --baseUrl https://blackbaud.github.io/skyux-pr-preview/${{ github.event.number }}/storybooks/${{ matrix.project }}/
        env:
          PERCY_TOKEN: ${{ secrets[matrix.token] }}
