name: Risk assessment
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
      - labeled
      - unlabeled
jobs:
  check_risk_labels:
    name: Check risk labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(label => label.name);
            if (labels.find(label => label.startsWith('autorelease'))) {
              console.log('Release PRs are not subject to risk assessment. ðŸš¢');
            } else {
              const authorRisk = labels.find(label => label.startsWith('risk level (author):'));
              const reviewerRisk = labels.find(label => label.startsWith('risk level (reviewer):'));
              if (authorRisk && reviewerRisk) {
                console.log('PR has both author and reviewer risk labels. Good luck. ðŸ«¡');
              } else {
                if (authorRisk) {
                  core.setFailed(`PR has author risk label but no reviewer risk label. ðŸ›‘`);
                } else if (reviewerRisk) {
                  core.setFailed(`PR has reviewer risk label but no author risk label. ðŸ›‘`);
                } else {
                  core.setFailed(`PR has no risk labels. ðŸ›‘`);
                }
              }
            }
