name: Storybook

on:
  push:
    branches:
      - main
      - 6.x.x

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('package-lock.json') }}
      - name: npm install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build Storybook
        run: npx nx run storybook:build
      - uses: actions/checkout@v3
        with:
          repository: 'blackbaud/skyux-storybook'
          ref: 'main'
          fetch-depth: 1
          path: skyux-storybook
          token: ${{secrets.GH_PERSONAL_ACCESS_TOKEN}}
      - name: Remove old branch builds
        run: |
          set -x
          ls -d ./skyux-storybook/*/ | cut -f3 -d/ | sort > ${{ runner.temp }}/current_builds.txt
          git branch -r --format '%(refname:lstrip=3)' | tr -d ' ' | sort > ${{ runner.temp }}/expected_builds.txt
          if [[ -s "${{ runner.temp }}/current_builds.txt" && -s "${{ runner.temp }}/expected_builds.txt" ]]
          then
            # Get current builds that are not in expected.
            comm -23 ${{ runner.temp }}/current_builds.txt ${{ runner.temp }}/expected_builds.txt | tr -d ' ' > ${{ runner.temp }}/old_builds.txt
            if [[ -s "${{ runner.temp }}/old_builds.txt" ]]
            then
              git -C ./skyux-storybook rm -r -f --pathspec-from-file=${{ runner.temp }}/old_builds.txt
            else
              echo "All builds are current"
            fi
          else
            echo "Nothing to remove"
          fi
        env:
          GITHUB_TOKEN: ${{secrets.GH_PERSONAL_ACCESS_TOKEN}}
      - name: Update branch build
        run: |
          set -x
          rm -rf ./skyux-storybook/${{ github.ref_name }}
          cp -R ./dist/storybook/storybook ./skyux-storybook/${{ github.ref_name }}
      - name: Commit build to GH Pages
        run: |
          set -x
          git config --global user.name "Blackbaud Sky Build User"
          git config --global user.email "sky-build-user@blackbaud.com"
          git -C ./skyux-storybook add --all
          git -C ./skyux-storybook status
          if [[ -n "$(git -C ./skyux-storybook status -s)" ]]
          then
            git -C ./skyux-storybook commit -m "$(printf 'skyux %s commit %s' ${{ github.ref_name }} ${GITHUB_SHA:0:8})"
            git -C ./skyux-storybook push
          else
            echo "No changes"
          fi
      - name: Percy
        run: npx percy storybook https://blackbaud.github.io/skyux-storybook/${{ github.ref_name }}/
        env:
          PERCY_TOKEN: ${{secrets.PERCY_TOKEN}}
